### ISSUE TITLE
Upgrade openssl to avoid a security vulnerability

### ISSUE THREAD

**Issue by sehkone** [aicers/giganto#804]
Dependabot [reported a moderate vulnerability in openssl.](https://github.com/aicers/giganto/security/dependabot/25). Need to release a new version using the recent version of openssl.

**Comment by sophie-cluml** [comment]
I think we do not need to urgently release a new giganto version just to resolve this openssl vulnerability, because openssl crate isn't really being used by giganto. I think this vulnerability alert will be handled when we release the next giganto version, by running `cargo update` as we are supposed to.

**Comment by kimhanbeom** [comment]
The issue has been resolved, so I'll close it.
